-- MySQL Script generated by MySQL Workbench
-- Thu Mar  7 20:58:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usertype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usertype` (
  `usertype_id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usertype_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `address_id` INT NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `city` VARCHAR(100) NOT NULL,
  `street` VARCHAR(100) NOT NULL,
  `street_number` VARCHAR(10) NOT NULL,
  `home_number` VARCHAR(10) NULL,
  `postal_code` CHAR(6) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(11) NULL,
  `user_usertype_id` INT NOT NULL,
  `user_address_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `user_usertype_id`, `user_address_id`),
  INDEX `fk_user_usertype_idx` (`user_usertype_id` ASC) VISIBLE,
  INDEX `fk_user_address_idx` (`user_address_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_usertype`
    FOREIGN KEY (`user_usertype_id`)
    REFERENCES `mydb`.`usertype` (`usertype_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_address`
    FOREIGN KEY (`user_address_id`)
    REFERENCES `mydb`.`address` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`phone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`phone` (
  `phone_id` INT NOT NULL,
  `manufacturer` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `processor` VARCHAR(45) NULL,
  `system` VARCHAR(45) NULL,
  `screen_size` VARCHAR(6) NULL,
  `ram` VARCHAR(5) NULL,
  `storage` VARCHAR(5) NULL,
  `camera` VARCHAR(25) NULL,
  `price` DECIMAL(7,2) NULL,
  PRIMARY KEY (`phone_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sale` (
  `sale_id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `date_order` DATE NOT NULL,
  `date_completed` DATE NULL,
  `sale_user_id` INT NOT NULL,
  `sale_product_id` INT NOT NULL,
  `sale_phone_id` INT NOT NULL,
  PRIMARY KEY (`sale_id`, `sale_user_id`, `sale_product_id`, `sale_phone_id`),
  INDEX `fk_sale_user_idx` (`sale_user_id` ASC) VISIBLE,
  INDEX `fk_sale_phone_idx` (`sale_phone_id` ASC) INVISIBLE,
  CONSTRAINT `fk_sale_user`
    FOREIGN KEY (`sale_user_id`)
    REFERENCES `mydb`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sale_phone`
    FOREIGN KEY (`sale_phone_id`)
    REFERENCES `mydb`.`phone` (`phone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
