insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-01-08', null, 3, 3, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-02-18', null, 6, 7, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-02-03', null, 4, 2, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-01-12', null, 3, 5, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-05-16', null, 6, 6, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-03-22', null, 6, 4, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-04-08', null, 2, 7, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-06-03', null, 2, 2, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-02-05', null, 3, 7, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-01-24', null, 5, 8, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-02-13', null, 5, 5, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-03-30', null, 4, 1, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-03-28', null, 2, 4, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-03-31', null, 6, 6, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-02-10', null, 5, 8, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-05-14', null, 5, 8, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-05-07', null, 6, 7, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-02-07', null, 2, 6, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-01-19', null, 5, 4, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-02-03', null, 5, 8, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-03-05', null, 3, 4, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-01-28', null, 2, 2, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-03-04', null, 1, 8, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-05-05', null, 2, 6, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-03-30', null, 4, 7, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-01-10', null, 5, 5, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-03-18', null, 4, 1, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-04-21', null, 3, 2, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-04-25', null, 4, 3, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-02-01', null, 4, 6, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-01-22', null, 4, 1, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-02-24', null, 5, 2, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-04-24', null, 5, 6, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-03-29', null, 3, 5, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-01-29', null, 4, 1, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-02-11', null, 6, 5, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-04-13', null, 2, 3, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-03-26', null, 2, 4, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-02-16', null, 2, 5, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-01-02', null, 3, 4, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-04-22', null, 2, 6, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-04-28', null, 4, 5, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-05-13', null, 5, 2, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-03-14', null, 5, 5, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-05-28', null, 4, 2, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-01-21', null, 1, 1, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-01-24', null, 4, 5, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-03-31', null, 1, 3, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-03-12', null, 2, 8, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-02-11', null, 4, 6, 4);
