insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-02-27', null, 6, 6, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-04-29', null, 1, 8, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-02-18', null, 1, 3, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-02-25', null, 1, 8, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-03-12', null, 3, 2, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-03-18', null, 2, 5, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-01-26', null, 3, 3, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-01-11', null, 4, 5, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-02-14', null, 2, 6, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-04-21', null, 4, 3, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-02-23', null, 3, 5, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-01-27', null, 6, 5, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-01-11', null, 6, 1, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-05-27', null, 2, 8, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-04-24', null, 1, 3, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-05-13', null, 1, 4, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-02-01', null, 1, 1, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-04-01', null, 6, 2, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-01-26', null, 3, 5, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-05-24', null, 3, 6, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-03-31', null, 6, 2, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-01-04', null, 4, 5, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-01-13', null, 1, 8, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-05-09', null, 3, 8, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-02-25', null, 6, 3, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-05-29', null, 6, 5, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-04-30', null, 2, 8, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-01-04', null, 2, 8, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-03-16', null, 6, 4, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-05-12', null, 6, 6, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-06-01', null, 2, 5, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-05-29', null, 3, 4, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-04-23', null, 4, 8, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-05-05', null, 6, 6, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-04-07', null, 1, 6, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-04-11', null, 3, 1, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'transfer', '2019-01-03', null, 2, 1, 6);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-05-09', null, 6, 1, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-01-04', null, 1, 2, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-06-04', null, 3, 2, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-02-24', null, 2, 4, 4);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-05-08', null, 2, 6, 3);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-03-15', null, 6, 1, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-03-21', null, 2, 5, 1);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'cash on delivery', '2019-02-08', null, 4, 4, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DPD', 'transfer', '2019-04-23', null, 2, 8, 5);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'cash on delivery', '2019-04-09', null, 6, 5, 8);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('Poczta polska', 'cash on delivery', '2019-02-15', null, 6, 5, 2);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-01-24', null, 6, 4, 7);
insert into sale (delivery, payment, date_order, date_completed, sale_user_id, sale_phone_id, quantity) values ('DHL', 'transfer', '2019-02-18', null, 2, 5, 4);
